Stringify 'queue' parameter in payload
StackStorm-Exchange/stackstorm-aws pull request #106
Opened 2020-05-17 09:39 UTC by stefangusa

Bug which alters the normal functioning of the sensor.

2020-05-17 11:18 UTC, nmaludy commented
Can you show an example of how this is broken?

I'm sure someone put in the urlunparse for a reason.

2020-05-17 12:15 UTC, stefangusa commented
@nmaludy Let me make a quick overview:

In #87 , I have added the multiaccount SQS sensor capability which allowed the usage of AWS SQS instances URL, along with the name. I have also implemented the unit tests, which now I change.

I have used my fork implementing that until the PR was merged. On my fork, I used to have a more naïve parsing of the URL, and [here](https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/sensors/sqs_sensor.py#L87), the `queue` parameter used to be a `string`. 

When reviewing, there was a suggestion to use `six` library to parse the URL and I had to change also the unit tests before merging, this is from where the `urlparse` appeared in the unit tests. The `queue` parameter [here](https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/sensors/sqs_sensor.py#L87) became a `six` object.

However, now when I tried to use the official setup, the trigger - which is mocked in the unit tests - cannot be triggered as the `queue` must be a `string`. So this is what I am trying to change now. The unit tests must be changed as a consequence.

I have already tested the change and works perfectly.

2020-05-18 15:56 UTC, nmaludy requested changes
Sounds good, you just need to bump the pack version in pack.yaml to 1.3.4

2020-05-18 16:19 UTC, nmaludy approved these changes

2020-05-18 16:19 UTC, merged