Autoscaling
StackStorm-Exchange/stackstorm-aws pull request #16
Opened 2017-02-17 16:48 UTC by AndyMoore111

autoscaling actions for aws 

slight change to lib/action.py to deserialise datetime's in responses

2017-02-17 17:42 UTC, Kami commented
Thanks.

We will look shortly when get a chance.

2017-02-20 08:22 UTC, userlocalhost requested changes

2017-02-21 12:16 UTC, AndyMoore111 commented on actions/lib/action.py
> +        formatted = json.loads(
thanks - new update should do this instead

2017-02-22 02:22 UTC, userlocalhost commented
Thank you for the correction, LGTM!
If possible, you should write tests for the additional actions.

2017-02-22 02:22 UTC, userlocalhost approved these changes

2017-02-22 21:42 UTC, AndyMoore111 commented
all these actions are generated - not sure if there's a good way to automate the tests as well but will have a look at options

2017-02-23 12:32 UTC, emedvedev commented
Thanks for the contribution! @userlocalhost approved, so merging.

2017-02-23 12:32 UTC, merged