Add boto3action to aws pack
StackStorm-Exchange/stackstorm-aws pull request #44
Opened 2017-07-31 19:42 UTC by xydinesh

I create this pull request as a result of discussion happened in, https://github.com/StackStorm-Exchange/exchange-incubator/pull/10. Main features in this pull request are,

- Ability to assume_role for  cross account access
- Ability to specify region for cross region access

For example, I have a st2 deployment in aws account 123456 and us-east-1. I want to deploy VPC in account 456789 and us-west-1.

```yaml
     assume_role:
        action: aws.assume_role
        input:
           role_arn: “arn:aws:iam:456789:role/st2_role”
        publish:
          credentials: <% task(assume_role).result.result %>
       on-success:
         - create_vpc
    
    create_vpc:
      action: aws.boto3action
      input:
        service: ec2
        action_name: create_vpc
        region: "us-west-1"
        params: <% dict(CidrBlock => "10.0.0.0/16", InstanceTenancy => "default") %>
        credentials: <% $.credentials %>
      publish:
          vpc_id: <% task(create_vpc).result.result.Vpc.VpcId %>
      on-success:
        - create_subnet

    create_subnet:
      action: aws.boto3action
      input:
        service: ec2
        region: "us-west-1"
        action_name: create_subnet
        params: <% dict(AvailabilityZone =>"us-west-1a", CidrBlock =>"10.0.0.0/24", VpcId => $.vpc_id) %>
        credentials: <% $.credentials %>
      publish:
        subnet_ids: <% task(create_subnets).result.result.Subnet.SubnetId %>
      on-success:
         - create_igw

     create_igw:
        action: aws.boto3action
        input:
          service: ec2
          action_name: create_internet_gateway
          region: <% $.region %>
          credentials: <% $.credentials %>
        publish:
          igw_id: <% task(create_igw).result.result.InternetGateway.InternetGatewayId %>

```

In addition, `aws.boto3action` created with following opinions.

* aws credentials
  Boto3 is the official SDK for AWS. As a user/developer, If I have boto3 configured I expect `aws` pack to work without doing any additional configuration. For example, 

```bash
st2 pack install aws
st2 run aws.boto3action service="ec2" action_name="decribe_vpcs" region="us-west-1"
```
In addition, if I want to use use boto3 profiles

```
st2 run aws.boto3action service="ec2" action_name="decribe_vpcs" region="us-west-1" env="AWS_PROFILE=production"
```

* yaml generation
  Long term, I don’t believe yaml generation scale based on the number of services AWS have and introduce. In addition, IMO Boto3 documentation is detailed, has examples. Having yaml for each action is redundant and add no value to the end user.

* pack maintenance

  Since there are no yaml to generate, this pack should be easy to maintain. Any new service boto3 introduce, available to pack user right away.

2017-07-31 23:36 UTC, warrenvw commented on boto3action.md
> +- Ablity to run cross region actions
Ablity -> Ability

2017-07-31 23:36 UTC, warrenvw commented on boto3action.md
> +- Ablility to run cross account actions.
Ability -> Ability

2017-07-31 23:38 UTC, warrenvw requested changes
I'm asking for a few minor tweaks. Before we merge `boto3` into `master`, we'll make sure that all outstanding issues are resolved, and users are notified of the upcoming changes.

2017-08-01 13:06 UTC, xydinesh commented on boto3action.md
> +- Ablity to run cross region actions
Fixed in the latest commit.

2017-08-01 13:08 UTC, xydinesh commented on boto3action.md
> +- Ablility to run cross account actions.
Fixed in the latest commit.

2017-08-04 05:57 UTC, warrenvw approved these changes

2017-08-07 20:05 UTC, xydinesh commented
@warrenvw Thanks for approving changes. Please let me know if you need anything from me to make progress on this PR.

2017-08-09 01:25 UTC, humblearner approved these changes
lgtm

2017-08-09 02:34 UTC, merged