Multiaccount SQS sensor capability
StackStorm-Exchange/stackstorm-aws pull request #87
Opened 2019-10-29 08:41 UTC by stefangusa

Fixes #83

2019-12-19 04:28 UTC, blag requested changes
Looking mostly good, but needs some improvements.

2019-12-19 09:25 UTC, stefangusa commented on sensors/sqs_sensor.py
> +        self.aws_region = self._get_config_entry('region')
This is the same code as the one existent now, just moved upwards, so I did not name these variables.

2019-12-19 23:37 UTC, blag commented on sensors/sqs_sensor.py
> +                    "eg: https://.../<account_id>"),
Now I'm thinking we should be even more explicit:
```suggestion
                    "eg: https://sqs.<aws_region>.amazonaws.com/<account_id>/<queue_name>"),
```

2019-12-19 23:37 UTC, blag commented on sensors/sqs_sensor.py
> +            if self._check_queue_if_url(queue):
```python
            self.input_queues = [six.moves.urllib.parse.urlparse(queue) for queue in queues]
```

Good compromise. :+1:

2019-12-19 23:41 UTC, blag approved these changes
One last tweak to exception message, but I think this is looking good.

2019-12-19 23:43 UTC, blag requested changes
Fixes for my own typos.

2019-12-19 23:43 UTC, blag commented on sensors/sqs_sensor.py
> +                    sys.exec_info()[2])
```suggestion
                    sys.exc_info()[2])
```

2019-12-19 23:43 UTC, blag commented on sensors/sqs_sensor.py
> +                    sys.exec_info()[2])
```suggestion
                    sys.exc_info()[2])
```

2019-12-20 09:55 UTC, stefangusa commented
And renamed 'roles_arns' to 'roles'.

2019-12-20 10:20 UTC, blag approved these changes
Thanks for seeing this through!

2020-04-09 18:04 UTC, nmaludy approved these changes
LGTM!

2020-04-09 18:05 UTC, nmaludy requested changes
Sorry two small changes.

Can you please add a CHANGELOG entry in: https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/CHANGES.md

And also bump the version in `pack.yaml` (https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/pack.yaml#L22) by 0.1  to be `1.3.0`.

Please and thank you!

After these two things i'll gladly merge!

2020-04-09 18:12 UTC, nmaludy commented on CHANGES.md
> +## 1.2.4
FYI the version here doesn't match the version in pack.yaml :( sorry!!!

```suggestion
## 1.3.0
```
You should be able to accept this suggestion and have it auto-commit the change.

2020-04-09 18:22 UTC, nmaludy approved these changes
LGTM

2020-04-09 18:22 UTC, merged